### ISSUE TITLE
Self Signed SSL with no verification support

### ISSUE THREAD

**Issue by starsoccer** [IDmedia/hass-unraid#10]
Currently my unraid server uses SSL/TLS but with a self signed certificate. It doesnt seem like there is currently a way to make this work with the addon as there is no way to add the certificate, or simply ignore verification

**Comment by PilaScat** [comment]
same here

**Comment by xebmin** [comment]
Hello,
This can be easily bypassed using unraid connect url. It works like a charm !!!

**Comment by louispires** [comment]
> Hello, This can be easily bypassed using unraid connect url. It works like a charm !!!

I tried this but still ran into some issues, with `ssl` set to `True`, I get the following error:
`websockets.exceptions.InvalidURI: https://10-0-0-250.abc123.myunraid.net:444/login isn't a valid URI: scheme isn't ws or wss`

With it set to `False`, I get this error:
`websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400`

Neither one seems to work for me...

My server is ONLY accessible via HTTPS and on port 444

**Comment by louispires** [comment]
nvm on the above, got it working after I debugged it and the following config worked:

```
unraid:
  - name: brute
    host: 10-0-0-250.abc123.myunraid.net
    port: 444
    ssl: True
    username: root
    password: PASSWORD
    scan_interval: 30
  
mqtt:
  host: 10.0.0.247
  port: 1883
  username: USERNAME
  password: PASSWORD
```
